[tool.ruff]
exclude = [".github", ".ruff_cache", ".vscode"]
fix = false
include = ["*.py"]
indent-width = 4
line-length = 120
output-format = "grouped"
respect-gitignore = true
src = ["src"]
target-version = "py311"

[tool.ruff.format]
docstring-code-format = false
docstring-code-line-length = "dynamic"
indent-style = "space"
line-ending = "lf"
quote-style = "single"
skip-magic-trailing-comma = false

[tool.ruff.lint]
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
exclude = []
fixable = ["ALL"]
ignore = [
  "F403", # import *
]
select = ["F", "E", "I", "N", "RUF", "UP", "W"]
unfixable = []

[tool.ruff.lint.flake8-quotes]
inline-quotes = "single"

[tool.ruff.lint.isort]
case-sensitive = true
combine-as-imports = true
force-single-line = false
length-sort = false
lines-after-imports = 2
lines-between-types = 1

[tool.ruff.lint.per-file-ignores]
"main.py" = ["E501"]
