name: Install Python & Deps
author: Amir Abdollahi

description: Install Python and project dependencies

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: "pip"
    - name: Install Deps
      run: |
        pip install -r requirements.txt
      shell: bash